### ISSUE TITLE
[DBInstance] All instances in a cluster are rebooted simultaneously 

### ISSUE THREAD

**Issue by stiak** [aws-cloudformation/aws-cloudformation-resource-providers-rds#232]
When updating parameter groups the [UpdateHandler](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/blob/master/aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java) detects the "pending-reboot" state and reboots the instance.  

The problem with this is that it ends up rebooting all instances in a cluster at the same time, meaning availability of the cluster is compromised.  Ideally the affected instances would be rebooted sequentially, maximising availability of the cluster.

As a workaround, we are:
- Separating cloud formation stacks containing parameter groups and instances
- Updating the parameter group stack when changes are needed
- Manually performing the reboot (with a failover for the writer) sequentially

**Comment by osdrv** [comment]
DBInstance resources referring to the same cluster are seen as the same hierarchical level objects with no inter-dependency between each other. From this perspective, CFN simply schedules up all updates at once and considers this to be a safe operation. It certainly doesn't make much sense from the DB cluster availability perspective.

This description implies that creating an inter-dependency between nodes will ensure updates are scheduled up in a cascade mode rather than all-at-once. Please refer to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html for more details.

We'll update this ticket if we get any updates on an automatic inter-dependency create for the cluster-instance hierarchy.

**Comment by osdrv** [comment]
After a consideration by the CFN core team, the conclusion is that declaring dependencies is much more practical compared to delegating the stack management flow control to a resource. Hence, the topology could be defined using an explicit `dependsOn` attributing on the instance objects. Hope this makes sense.
